#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

import agent

json.load(sys.stdin)
agent.remove_public_service(os.environ["MODULE_ID"])
