#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

import agent
import agent.tasks

json.load(sys.stdin)
module_id = os.environ["MODULE_ID"]
traefik_id = agent.resolve_agent_id("traefik@node")
if traefik_id is not None:
    agent.tasks.run(agent_id=traefik_id, action="delete-route", data={"instance": module_id})
agent.remove_public_service(module_id)
